config/routes.rb
Members::Application.routes.draw do
  root 'check_in#checkin_page'

  get 'checkin', to: 'check_in#checkin_page'
  get 'checkin/histories', to: 'check_in#histories'
  post 'checkin', to: 'check_in#checkin'

  resources 'checkin', controller: "check_in", only: [:edit, :destroy, :update], as: "check_in"

  resources 'members', only: [:index, :show, :update, :create, :new, :destroy] do
    get 'edit', to: 'members#edit'
    get 'destroy_confirm'

    resources 'membership_registrations', only: [:create, :edit, :update, :new]

    delete 'avatar', to: 'avatar#destroy', as: :destroy_avatar
  end

  resources 'activities', only: [:index, :show, :update, :create, :new] do
    get 'edit', to: 'activites#edit'
  end

  resources 'sessions', only: [:create, :destroy, :new]
  get 'sessions/signout', to: 'sessions#destroy'

  resources 'course_instructors', only: [:index, :show, :update, :create, :new, :edit] do
  end

  get 'courses/calendar', to: 'courses#calendar'
  get 'courses/today', to: 'courses#today'
  get 'courses/:course_id/duplicate', to: 'courses#duplicate', as: :course_duplicate

  resources 'courses' do
    resources 'course_attendances', only: [:edit, :show, :update, :destroy]

    get 'member/:id/course_class/edit', to: 'course_class_memberships#edit', as: :edit_membership
    post 'member/:id/course_class', to: 'course_class_memberships#update', as: :update_membership

    resources 'course_classes', only: [:edit, :update, :destroy, :show, :new, :create]

    post 'update_attendance'
    post 'regenerate_classes'
  end

  get 'email_list_generator', :controller => :utils, :action => :email_list_generator

  resources 'course_registrations' do
    collection do
      get 'new_registration'
      post 'create_registration'
    end
  end

  resources 'books' do
    collection do
      get 'new_registration'
      post 'create_registration'
    end
    member do
      get 'mark_as_returned'
    end
  end

  resources 'book_rentals', :only => [:edit, :update, :create, :new] do
    collection do
      get 'return_a_book'
      post 'return_a_book', :to => 'book_rentals#do_return'
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < AuthenticatedController
  skip_before_action :authenticate_user!, only: [:show, :index, :calendar, :today]

  before_action -> { @session = session }
  before_action -> { @course = Course.find(params[:id]) }, only: [:show, :edit, :update]
  before_action -> { @course = Course.find(params[:course_id]) }, only: [:update_attendance, :regenerate_classes]

  def new
  end

  def edit
  end

  def duplicate
    existing_course = Course.find(params[:course_id])
    @course = existing_course.duplicate
    render :new
  end

  def index
    set_grid
  end

  def calendar
    respond_to do |format|
      format.json {
        @events = []
        if params[:start].present? && params[:end].present?
          @events = Course.at_location(@location).events(Date.parse(params[:start]), Date.parse(params[:end]))
        end
        render json: @events
      }
      format.html {}
    end
  end

  def create
    @course = Course.create(course_params)
    @course.start_time = Time.zone.parse(course_params[:start_time])
    @course.end_time = Time.zone.parse(course_params[:end_time])
    @course.generate_classes if @course.errors.blank?
    flash[:notice] = "#{@course.course_name} created successfully" if @course.errors.nil? || @course.errors.empty?
    set_grid
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def show
    set_members_grid
    set_course_attendance_grid
    set_course_class_grid
    @tab = params[:tab]
    respond_to do |format|
      format.json {}
      format.html {}
      format.xls do
        spreadsheet = StringIO.new
        name, book = @course.to_xls
        book.write spreadsheet
        send_data spreadsheet.string, :filename => name, :type =>  "application/vnd.ms-excel"
      end
    end
  end

  def update
    p = course_params
    p[:start_time] = Time.parse(course_params[:start_time])
    p[:end_time] = Time.parse(course_params[:end_time])
    @course.update(p)

    flash[:notice] = "#{@course.course_name} updated successfully" if @course.errors.nil? || @course.errors.empty?
    set_grid
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def today
    @classes = CourseClass.for_today(@location)
    @classes_grid = initialize_grid(@classes,
                                    include: {course: :location},
                                    order: 'start_time',
                                    order_direction: 'asc')
  end

  def update_attendance
    attendances = params[:attendance] || []
    begin
      existing_attendances = @course.course_attendances.to_a

      attendances.each do |cclass_id, members|
        cclass = CourseClass.find(cclass_id)
        existing_members = cclass.members
        members.select{|id, s| s}.each do |member_id, selected|
          member = Member.find(member_id)
          if existing_members.include? member
            existing_attendances.delete_if do |e|
              e.member == member && cclass_id.to_i == e.course_class.id
            end
          else
            CourseAttendance.create!({
              course_class: cclass,
              member: member
            })
          end
        end
      end

      existing_attendances.each do |e|
        e.destroy!
      end
    rescue => e
      flash[:error] = e.to_s
      redirect_to course_path(@course, tab: 'attendance') and return
    end

    flash[:notice] = 'Saved'
    redirect_to course_path(@course, tab: 'attendance') and return
  end

  def regenerate_classes
    raise "Cannot generate classes after it has started" if is_started?
    @course.course_classes.each {|a| a.mark_as_cancelled}
    @course.generate_classes
    redirect_to @course
  end

  private
  def set_members_grid
    @course_member_grid = initialize_grid(@course.course_registrations,
                                          name: 'member_grid',
                                          include: [:member],
                                          order: 'created_at',
                                          order_direction: 'desc')
  end

  def set_grid
    courses = Course.at_location(@location)
    unless params[:show_all] == 'true'
      courses = courses.where('end_date >= NOW()')
    end

    @courses_grid = initialize_grid(courses,
                                    include: [:location],
                                    order: 'start_date',
                                    order_direction: 'desc')
  end

  def set_course_class_grid
    @course_classes_grid = initialize_grid(@course.course_classes.active,
                                           name: 'class_grid',
                                           order: 'start_time',
                                           order_direction: 'desc')
  end

  def set_course_attendance_grid
    @course_attendances_grid = initialize_grid(@course.course_attendances,
                                               name: 'attendance_grid',
                                               order: 'created_at',
                                               order_direction: 'desc')
  end

  def course_params
    params.require(:course).permit(:course_code, :course_name, :day_of_week, :course_fee_general, :course_fee_senior_circle, :course_fee_volunteer, :start_date, :start_time, :end_date, :end_time ,:description, :number_of_lessons, :course_instructor_id, :course_description, :course_chinese_name, :location_id)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/show/_course_attendances.html.erb
<style>
  attendance-table.table {
    text-align: center;
  }
</style>
<%= form_tag(course_update_attendance_path(course),
             method: :post,
             class: 'attendance-form') do %>
  <%= submit_tag 'Update', class: 'small button' %>
  <table class='attendance-table'>
    <thead>
      <tr>
        <th>Card Number</th>
        <th>Member Name</th>
        <th>Chinese Name</th>
        <% course.course_classes.each do |cclass| %>
          <th><%= cclass.date %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <%= hidden_field_tag 'course_id', course.id %>
      <% course.members.each do |member| %>
        <tr>
          <td> <%= member.card_number %> </td>
          <td> <%= link_to member.fullname, member %> </td>
          <td> <%= link_to member.chinese_name, member %> </td>
          <% course.course_classes.each do |cclass| %>
            <td>
              <% if cclass.is_member?(member) %>
                <%= check_box_tag "attendance[#{cclass.id}][#{member.id}]", nil, cclass.attended?(member) %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<% unless @authenticated %>
  <script>
    $('.attendance-form input').attr('disabled', 'disabled');
  </script>
<% end %>

app/views/courses/show/_course_classes.html.erb
<% if course.course_classes.active.count != course.number_of_lessons %>
  <span class='warning' style='font-weight: bold; color: red'>There are <%= course.course_classes.active.count %> classes scheduled but <%= course.number_of_lessons %> is expected.</span>
<% end %>
<div style='margin-top: 10px'>
  <%= link_to_modal("New", new_course_course_class_path(course), class: 'button small') if @session[:authenticated] %>
  <% unless course.is_started? %>
    <%= link_to("Regenerate classes", course_regenerate_classes_path(course), class: 'button small', method: :post) if @session[:authenticated] %>
  <% end %>
</div>
<%= grid(course_classes_grid, html: { style: 'width: 100%' }) do |g|
  g.column name: 'Start Time', attribute: 'start_time' do |course_class|
    course_class.start_time.to_est.strftime("%Y-%m-%d %l:%M %P")
  end

  g.column name: 'End Time', attribute: 'end_time' do |course_class|
    course_class.end_time.to_est.strftime("%Y-%m-%d %l:%M %P")
  end

  g.column name: 'Attendance' do |course_class|
    course_class.course_attendances.count
  end

  g.column in_csv: false do |course_class|
    if @session[:authenticated]
      (link_to_modal 'Edit', edit_course_course_class_path(course_class.course, course_class)) + " " +
        (link_to "Cancel", course_course_class_path(course_class.course, course_class), :method => 'delete', remote: true)
    end
  end
end
%>

app/views/courses/show/_info.html.erb
<table class="course-info-table">
   <tr>
     <td>
       <div class="row">
         <div class="columns large-6">
           <h6><strong>Course code:</strong></h6>
         </div>
         <div class="columns large-6">
           <%= course[:course_code] %>
         </div>
       </div>
     </td>
     <td>
       <div class="row">
         <div class="columns large-6">
           <h6><strong>Period:</strong></h6>
         </div>
         <div class="columns large-6">
           <%= course[:start_date] %> - <%= course[:end_date] %>
         </div>
       </div>
     </td>
     <td>
       <div class="row">
         <div class="columns large-6">
           <h6><strong>Time:</strong></h6>
         </div>
         <div class="columns large-6">
           <%= course.start_time_value %> - <%= course.end_time_value %>
         </div>
       </div>
     </td>
     <td>
       <div class="row">
         <div class="columns large-6">
           <h6><strong>Day of Week:</strong></h6>
         </div>
         <div class="columns large-6">
           <%= Course::DayOfWeek::WEEK[course[:day_of_week]] %>
         </div>
       </div>
     </td>
   </tr>

  <% fields = [:number_of_lessons, :course_fee_senior_circle, :course_fee_general, :course_fee_volunteer]
   columns = 4 %>

 <% fields_per_column = (fields.count / columns.to_f).ceil
 fields.each_slice(fields_per_column).to_a.reduce([]) do |rows, column|
   column.each_index do |index|
     rows[index] ||= []
     rows[index] << column[index]
   end
   rows
 end.each do | fields | %>
     <tr>
     <% fields.each do | field | %>
       <td>
         <div class="row">
           <div class="columns large-6">
             <h6><strong><%= field.to_s.split('_').map {|x|x.capitalize}.join(' ').strip %>:</strong></h6>
           </div>
           <div class="columns large-6">
             <%= course[field] %>
           </div>
         </div>
       </td>
     <% end %>
     </tr>
<% end %>
</table>