config/routes.rb
Members::Application.routes.draw do
  root 'check_in#checkin_page'

  get 'checkin', to: 'check_in#checkin_page'
  get 'checkin/histories', to: 'check_in#histories'
  post 'checkin', to: 'check_in#checkin'

  resources 'checkin', controller: "check_in", only: [:edit, :destroy, :update], as: "check_in"

  resources 'members', only: [:index, :show, :update, :create, :new, :destroy] do
    get 'edit', to: 'members#edit'
    get 'destroy_confirm'

    resources 'membership_registrations', only: [:create, :edit, :update, :new]

    delete 'avatar', to: 'avatar#destroy', as: :destroy_avatar
  end

  resources 'activities', only: [:index, :show, :update, :create, :new] do
    get 'edit', to: 'activites#edit'
  end

  resources 'sessions', only: [:create, :destroy, :new]
  get 'sessions/signout', to: 'sessions#destroy'

  resources 'course_instructors', only: [:index, :show, :update, :create, :new, :edit] do
  end

  get 'courses/calendar', to: 'courses#calendar'
  get 'courses/today', to: 'courses#today'
  get 'courses/:course_id/duplicate', to: 'courses#duplicate', as: :course_duplicate

  resources 'courses' do
    resources 'course_attendances', only: [:edit, :show, :update, :destroy]

    get 'member/:id/course_class/edit', to: 'course_class_memberships#edit', as: :edit_membership
    post 'member/:id/course_class', to: 'course_class_memberships#update', as: :update_membership

    resources 'course_classes', only: [:edit, :update, :destroy, :show, :new, :create]

    post 'update_attendance'
    post 'regenerate_classes'
  end

  get 'email_list_generator', :controller => :utils, :action => :email_list_generator

  resources 'course_registrations' do
    collection do
      get 'new_registration'
      post 'create_registration'
    end
  end

  resources 'books' do
    collection do
      get 'new_registration'
      post 'create_registration'
    end
    member do
      get 'mark_as_returned'
    end
  end

  resources 'book_rentals', :only => [:edit, :update, :create, :new] do
    collection do
      get 'return_a_book'
      post 'return_a_book', :to => 'book_rentals#do_return'
    end
  end
end

app/models/course_instructor.rb
class CourseInstructor < ActiveRecord::Base
  has_paper_trail
  validates :name, presence: true

  has_many :courses, inverse_of: :course_instructor

  XLS_FIELDS = [:name, :chinese_name, :info]

  def self.to_xls
    date = DateTime.now
    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet name: 'Instructors Info'

    sheet1.row(0).replace(XLS_FIELDS.map {|x| x.to_s.split('_').map {|s| s.capitalize}.join(' ')})
    index = 1
    self.all.each do | member |
      sheet1.row(index).replace(XLS_FIELDS.map {|x| member[x]})
      index += 1
    end

    return "all_#{self.name.underscore}_#{date.strftime('%Y%m%d')}.xls", book
  end
end

app/controllers/course_instructors_controller.rb
class CourseInstructorsController < AuthenticatedController
  before_action -> { @session = session }
  before_action -> { @course_instructor = CourseInstructor.find(params[:id]) }, only: [:show, :update, :edit]

  skip_before_action :authenticate_user!, only: [:show, :index]

  def index
    set_instructors_grid
  end

  def new
  end

  def edit
  end

  def create
    @new_instructor = CourseInstructor.new(create_params)
    @new_instructor.save

    flash[:notice] = "#{@new_instructor.name} created successfully" if @new_instructor.errors.nil? || @new_instructor.errors.empty?
    set_instructors_grid
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def update
    @course_instructor.update!(create_params)

    flash[:notice] = "#{@course_instructor.name} updated successfully" if @course_instructor.errors.nil? || @course_instructor.errors.empty?
    set_instructors_grid
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def show
    @courses_grid = initialize_grid(@course_instructor.courses)
  end

  private
  def set_instructors_grid
    @course_instructors_grid = initialize_grid(CourseInstructor,
                                      name: 'instructors1')
  end

  def create_params
    params.require(:course_instructor).permit(:name, :chinese_name, :info)
  end
end

app/helpers/course_instructors_helper.rb
module CourseInstructorsHelper
end

app/views/course_instructors/_course_instructors.html.erb
<%= grid(@course_instructors_grid, html: { style: 'width: 100%' }) do |g|
  g.column name: 'Name', attribute: 'name' do |course_instructor|
    course_instructor.name
  end

  g.column name: 'Chinese name', attribute: 'chinese_name' do |course_instructor|
    course_instructor.chinese_name
  end

  g.column in_csv: false do |course_instructor|
    (link_to 'Show', course_instructor) + ' ' +
    if @session[:authenticated]
      (link_to_modal 'Edit', edit_course_instructor_path(course_instructor))
    else
      ''
    end
  end
end
%>

app/views/course_instructors/_form.html.erb
<% course_instructor = CourseInstructor.new unless course_instructor %>
<div class="modal-form" id="course-instructor-form">
  <%= form_for(course_instructor, remote: true, style: 'overflow: scroll') do |f| %>
    <%= f.text_field :name %>
    <%= f.text_field :chinese_name %>
    <%= f.text_area :info, rows: 7 %>
    <%= f.submit %>
  <% end %>
</div>

app/views/course_instructors/_info.html.erb
<h1>
  <%= course_instructor.name %>
</h1>
<h1>
  <%= course_instructor.chinese_name %>
</h1>

app/views/course_instructors/create.js.erb
<% if @new_instructor.errors.empty? %>
  $.modal.close();
  $("#course-instructors-table").html('<%= escape_javascript(render(partial: "course_instructors")) %>')
  $('#flash').html("<%= escape_javascript raw(flash_display) %>");
  $('#flash').show();
<% else %>
  $("#new-instructor").html('<%= escape_javascript(render(partial: "form", locals: { course_instructor: @new_instructor })) %>');
<% end %>

app/views/course_instructors/edit.html.erb
<div id="edit-instructor">
  <%= render partial: "form", locals: { course_instructor: @course_instructor } %>
</div>

app/views/course_instructors/index.html.erb
<div class="row">
  <div class="small-8 large-centered columns">
    <h1 style='text-align: center'>All Instructors:</h1>
  </div>
</div>
<div class="row">
  <div class="small-10 large-centered columns" style="padding-bottom: 10px">
    <%= link_to_modal("New", new_course_instructor_path, class: 'button small') if @session[:authenticated] %>
    <%= link_to("Export", course_instructors_path(format: :xls), class: 'button small') if @session[:authenticated] %>
  </div>
</div>
<div class="row">
  <div class="small-10 large-centered columns" id="course-instructors-table">
    <%= render partial: "course_instructors", locals: { course_instructors: @course_instructors } %>
  </div>
</div>

app/views/course_instructors/new.html.erb
<div id="new-instructor">
  <%= render partial: "form" %>
</div>

app/views/course_instructors/show.html.erb
<div class='row'>
  <div class='column large-12'>
    <h2><%= @course_instructor.name %> (<%= @course_instructor.chinese_name %>)</h2>
    <%= @course_instructor.info %>
    <hr/>
  </div>
</div>
<div class='row'>
  <div class='column large-12'>
    <h3>Courses</h3>
  </div>
  <%= grid(@courses_grid, html: { style: 'width: 100%' }) do |g|
    g.column name: 'Name', attribute: 'course_name'
    g.column name: 'Chinese name', attribute: 'course_chinese_name'
    g.column name: 'Period', attribute: 'start_date' do |course|
      "#{course.start_date} - #{course.end_date}"
    end
    g.column name: 'Time', attribute: 'start_time' do |course|
      "#{course.start_time_value} - #{course.end_time_value}"
    end

    g.column in_csv: false do |course|
      link_to 'Show', course
    end
  end
  %>
</div>

app/views/course_instructors/update.js.erb
<% if @course_instructor.errors.empty? %>
  $.modal.close();
  $("#course-instructors-table").html('<%= escape_javascript(render(partial: "course_instructors")) %>')
  $('#flash').html("<%= escape_javascript raw(flash_display) %>");
  $('#flash').show();
<% else %>
  $("#edit-instructor").html('<%= escape_javascript(render(partial: "form", locals: { course_instructor: @course_instructor })) %>');
<% end %>