config/routes.rb
Members::Application.routes.draw do
  root 'check_in#checkin_page'

  get 'checkin', to: 'check_in#checkin_page'
  get 'checkin/histories', to: 'check_in#histories'
  post 'checkin', to: 'check_in#checkin'

  resources 'checkin', controller: "check_in", only: [:edit, :destroy, :update], as: "check_in"

  resources 'members', only: [:index, :show, :update, :create, :new, :destroy] do
    get 'edit', to: 'members#edit'
    get 'destroy_confirm'

    resources 'membership_registrations', only: [:create, :edit, :update, :new]

    delete 'avatar', to: 'avatar#destroy', as: :destroy_avatar
  end

  resources 'activities', only: [:index, :show, :update, :create, :new] do
    get 'edit', to: 'activites#edit'
  end

  resources 'sessions', only: [:create, :destroy, :new]
  get 'sessions/signout', to: 'sessions#destroy'

  resources 'course_instructors', only: [:index, :show, :update, :create, :new, :edit] do
  end

  get 'courses/calendar', to: 'courses#calendar'
  get 'courses/today', to: 'courses#today'
  get 'courses/:course_id/duplicate', to: 'courses#duplicate', as: :course_duplicate

  resources 'courses' do
    resources 'course_attendances', only: [:edit, :show, :update, :destroy]

    get 'member/:id/course_class/edit', to: 'course_class_memberships#edit', as: :edit_membership
    post 'member/:id/course_class', to: 'course_class_memberships#update', as: :update_membership

    resources 'course_classes', only: [:edit, :update, :destroy, :show, :new, :create]

    post 'update_attendance'
    post 'regenerate_classes'
  end

  get 'email_list_generator', :controller => :utils, :action => :email_list_generator

  resources 'course_registrations' do
    collection do
      get 'new_registration'
      post 'create_registration'
    end
  end

  resources 'books' do
    collection do
      get 'new_registration'
      post 'create_registration'
    end
    member do
      get 'mark_as_returned'
    end
  end

  resources 'book_rentals', :only => [:edit, :update, :create, :new] do
    collection do
      get 'return_a_book'
      post 'return_a_book', :to => 'book_rentals#do_return'
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < AuthenticatedController
  skip_before_action :authenticate_user!, only: [:show, :index, :calendar, :today]

  before_action -> { @session = session }
  before_action -> { @course = Course.find(params[:id]) }, only: [:show, :edit, :update]
  before_action -> { @course = Course.find(params[:course_id]) }, only: [:update_attendance, :regenerate_classes]

  def new
  end

  def edit
  end

  def duplicate
    existing_course = Course.find(params[:course_id])
    @course = existing_course.duplicate
    render :new
  end

  def index
    set_grid
  end

  def calendar
    respond_to do |format|
      format.json {
        @events = []
        if params[:start].present? && params[:end].present?
          @events = Course.at_location(@location).events(Date.parse(params[:start]), Date.parse(params[:end]))
        end
        render json: @events
      }
      format.html {}
    end
  end

  def create
    @course = Course.create(course_params)
    @course.start_time = Time.zone.parse(course_params[:start_time])
    @course.end_time = Time.zone.parse(course_params[:end_time])
    @course.generate_classes if @course.errors.blank?
    flash[:notice] = "#{@course.course_name} created successfully" if @course.errors.nil? || @course.errors.empty?
    set_grid
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def show
    set_members_grid
    set_course_attendance_grid
    set_course_class_grid
    @tab = params[:tab]
    respond_to do |format|
      format.json {}
      format.html {}
      format.xls do
        spreadsheet = StringIO.new
        name, book = @course.to_xls
        book.write spreadsheet
        send_data spreadsheet.string, :filename => name, :type =>  "application/vnd.ms-excel"
      end
    end
  end

  def update
    p = course_params
    p[:start_time] = Time.parse(course_params[:start_time])
    p[:end_time] = Time.parse(course_params[:end_time])
    @course.update(p)

    flash[:notice] = "#{@course.course_name} updated successfully" if @course.errors.nil? || @course.errors.empty?
    set_grid
    respond_to do |format|
      format.js {}
      format.html {}
    end
  end

  def today
    @classes = CourseClass.for_today(@location)
    @classes_grid = initialize_grid(@classes,
                                    include: {course: :location},
                                    order: 'start_time',
                                    order_direction: 'asc')
  end

  def update_attendance
    attendances = params[:attendance] || []
    begin
      existing_attendances = @course.course_attendances.to_a

      attendances.each do |cclass_id, members|
        cclass = CourseClass.find(cclass_id)
        existing_members = cclass.members
        members.select{|id, s| s}.each do |member_id, selected|
          member = Member.find(member_id)
          if existing_members.include? member
            existing_attendances.delete_if do |e|
              e.member == member && cclass_id.to_i == e.course_class.id
            end
          else
            CourseAttendance.create!({
              course_class: cclass,
              member: member
            })
          end
        end
      end

      existing_attendances.each do |e|
        e.destroy!
      end
    rescue => e
      flash[:error] = e.to_s
      redirect_to course_path(@course, tab: 'attendance') and return
    end

    flash[:notice] = 'Saved'
    redirect_to course_path(@course, tab: 'attendance') and return
  end

  def regenerate_classes
    raise "Cannot generate classes after it has started" if is_started?
    @course.course_classes.each {|a| a.mark_as_cancelled}
    @course.generate_classes
    redirect_to @course
  end

  private
  def set_members_grid
    @course_member_grid = initialize_grid(@course.course_registrations,
                                          name: 'member_grid',
                                          include: [:member],
                                          order: 'created_at',
                                          order_direction: 'desc')
  end

  def set_grid
    courses = Course.at_location(@location)
    unless params[:show_all] == 'true'
      courses = courses.where('end_date >= NOW()')
    end

    @courses_grid = initialize_grid(courses,
                                    include: [:location],
                                    order: 'start_date',
                                    order_direction: 'desc')
  end

  def set_course_class_grid
    @course_classes_grid = initialize_grid(@course.course_classes.active,
                                           name: 'class_grid',
                                           order: 'start_time',
                                           order_direction: 'desc')
  end

  def set_course_attendance_grid
    @course_attendances_grid = initialize_grid(@course.course_attendances,
                                               name: 'attendance_grid',
                                               order: 'created_at',
                                               order_direction: 'desc')
  end

  def course_params
    params.require(:course).permit(:course_code, :course_name, :day_of_week, :course_fee_general, :course_fee_senior_circle, :course_fee_volunteer, :start_date, :start_time, :end_date, :end_time ,:description, :number_of_lessons, :course_instructor_id, :course_description, :course_chinese_name, :location_id)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_courses.html.erb
<%= grid(courses_grid, html: { style: 'width: 100%' }) do |g|
  g.column name: 'Course Code', attribute: 'course_code'
  g.column name: 'Course Name', attribute: 'course_name'
  g.column name: 'Chinese Name', attribute: 'course_chinese_name'
  g.column name: 'Start Date', attribute: 'start_date'
  g.column name: 'End Date', attribute: 'end_date'
  g.column name: 'Day of Week', attribute: 'day_of_week' do |course|
    Course::DayOfWeek.for(course.day_of_week)
  end

  g.column name: 'Location', model: 'Location', attribute: 'name' do |activity|
    activity.location.display_name
  end

  g.column in_csv: false do |course|
    (link_to 'Show', course) + ' ' +
    if @session[:authenticated]
      (link_to_modal 'Edit', edit_course_path(course))
    else
      ''
    end
  end
end
%>

app/views/courses/_form.html.erb
<% course = Course.new unless course %>
<div class="modal-form" id="course-form">
  <%= form_for(course, remote: true, style: 'overflow: scroll') do |f| %>
    <%= f.label 'Instructor' %>
    <%= f.collection_select :course_instructor_id, CourseInstructor.order(:name), :id, :name, prompt: 'Select Instructor' %>
    <%= f.label 'Location' %>
    <%= f.collection_select :location_id, Location.order(:name), :id, :display_name, prompt: 'Select Location' %>
    <% [:course_code, :course_name, :course_chinese_name, :number_of_lessons, :course_fee_general, :course_fee_senior_circle, :course_fee_volunteer].each do |field| %>
      <%= f.text_field field %>
    <% end %>
    <%= f.label 'Day of Week' %>
    <%= select 'course', 'day_of_week', Course::DayOfWeek::WEEK.invert, prompt: 'Select Day' %>
    <%= f.text_field :start_date, class: 'date-input' %>
    <%= f.text_field :end_date, class: 'date-input' %>
    <%= f.text_field :start_time, value: course.start_time_value, class: 'time-input' %>
    <%= f.text_field :end_time, value: course.end_time_value, class: 'time-input' %>
    <%= f.text_area :course_description, rows: 8 %>
    <%= f.submit %>
  <% end %>
</div>
<script type='text/javascript'>
  $('.time-input').timepicker({timeFormat: 'HH:mm'});
  $('.date-input').datepicker({dateFormat: 'yy-mm-dd'});
</script>

app/views/courses/calendar.html.erb
<style type="text/css">
  #calendar .fc-header { border: 0px }
  #calendar .fc-border-separate { border: 0px }
</style>
<div class='row' style='margin-top: 20px'>
  <div id='calendar' class='large-12 large-centered columns'>
  </div>
</div>
<script>
  $('#calendar').fullCalendar({
    header: {
      left: 'prev,next today',
      center: 'title',
      right: 'month,agendaWeek,agendaDay'
    },
    events: '/courses/calendar.json'
  });
</script>

app/views/courses/create.js.erb
<% if @course.errors.empty? %>
  $.modal.close();
  $("#courses-table").html('<%= escape_javascript(render(partial: "courses", locals: { courses_grid: @courses_grid})) %>')
  $('#flash').html("<%= escape_javascript raw(flash_display) %>");
  $('#flash').show();
<% else %>
  $("#new-course").html('<%= escape_javascript(render(partial: "form", locals: { course: @course })) %>');
<% end %>

app/views/courses/edit.html.erb
<div id="edit-course">
  <%= render partial: "form", locals: { course: @course } %>
</div>

app/views/courses/index.html.erb
<div class="row">
  <div class="small-8 large-centered columns">
    <h1 style='text-align: center'>All Courses:</h1>
  </div>
</div>
<div class="row">
  <div class="small-10 large-centered columns" style="padding-bottom: 10px">
    <%= link_to_modal("New", new_course_path, class: 'button small') if @session[:authenticated] %>
    <%= link_to("Export Course Member", course_registrations_path(:format => 'xls'), class: 'button small') if @session[:authenticated] %>
    <!--    <%= link_to("Export", courses_path(format: :xls), class: 'button small') if @session[:authenticated] %> -->
    <br/>
    <% if params[:show_all] == 'true' %>
      <%= link_to 'Show Active Only', params.merge(:show_all => false) %>
    <% else %>
      <%= link_to 'Show All', params.merge(:show_all => true) %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="small-10 large-centered columns" id="courses-table">
    <%= render partial: "courses", locals: { courses_grid: @courses_grid } %>
  </div>
</div>

app/views/courses/new.html.erb
<div id="new-course">
  <%= render partial: "form", locals: {course: @course} %>
</div>

app/views/courses/show.html.erb
<script>
  $(function() {
    $('.pagination a').click(function() {
      $(this).attr('href', $(this).attr('href') + window.location.hash)
    });
    $('.pagination_status a').click(function() {
      $(this).attr('href', $(this).attr('href') + window.location.hash)
    });
  });
</script>
<style>
  .modal {
    width: 900px;
  }
</style>
<div class='row'>
  <div class='column large-8'>
    <h2><%= @course.course_name %> <%= @course.course_chinese_name %></h2>
  </div>
  <div class='column large-4 right'>
    <div class='right'>
      <%= link_to 'Export', course_path(@course, :format => 'xls'), class: 'button small', style: 'margin-top: 10px' if @session[:authenticated] %>
      <%= link_to_modal 'Create new', course_duplicate_path(@course), class: 'button small', style: 'margin-top: 10px' if @session[:authenticated] %>
    </div>
  </div>
</div>
<div class='row' style='padding-bottom: 10px'>
  <div class='column large-12'>
    <strong>Location:</strong>
  </div>
</div>
<div class='row' style='padding-bottom: 10px'>
  <div class='column large-12'>
  <%= @course.location.display_name %>
  </div>
</div>
<div class='row' style='padding-bottom: 10px'>
  <div class='column large-12'>
    <strong>Instructor:</strong>
  </div>
</div>
<div class='row' style='padding-bottom: 10px'>
  <div class='column large-12'>
    <%= link_to @course.course_instructor.name, @course.course_instructor %>
  </div>
</div>
<div class='row' style='padding-bottom: 10px'>
  <div class='column large-12'>
    <strong>Description:</strong>
  </div>
</div>
<div class='row' style='padding-bottom: 10px'>
  <div class='column large-12'>
    <%= @course.course_description %>
  </div>
</div>
<div class='row'>
  <div class='column large-12'>
    <%= render partial: 'courses/show/info', locals: { course: @course } %>
  </div>
</div>
<div class='row'>
  <div class='column large-12'>
    <hr/>
    <dl class="tabs" data-tab data-options="deep_linking:true" data-options="scroll_to_content: false">
      <dd class='<%= @tab.nil? || @tab == 'schedule' ? 'active' : '' %>'>
        <a href="#course-classes-table">Class Schedules</a>
      </dd>
      <dd><a href="#course-members">Course Members</a></dd>
      <dd class='<%= @tab == 'attendance' ? 'active' : '' %>'>
        <a href="#course-attendance-history">Attendance History</a>
      </dd>
    </dl>
    <div class="tabs-content">
      <div class='course-members content' id='course-members'>
        <% if @session[:authenticated] %>
          <%= link_to_modal('New Member', new_registration_course_registrations_path(course_id: @course.id), :class => 'button small') %>
        <% end %>
        <%= grid(@course_member_grid, html: {style: 'width: 100%'}) do |g|
          g.column name: 'Member card number', attribute: 'card_number', model: Member do |registration|
            registration.member.card_number
          end
          g.column name: 'Member name', attribute: 'first_name', model: Member do |registration|
            link_to registration.member.fullname, registration.member
          end
          g.column name: 'Chinese name', attribute: 'chinese_name', model: Member do |registration|
            link_to registration.member.chinese_name, registration.member
          end
          g.column name: 'Registration Date', attribute: 'created_at'
          g.column name: 'Amount Paid', attribute: 'amount_paid'
          g.column name: 'Receipt Number', attribute: 'receipt_number'
          g.column name: 'Remarks', attribute: 'remarks'

          g.column in_csv: false do |registration|
            if @session[:authenticated]
              (link_to_modal 'Edit',
               edit_course_registration_path(registration)
              ) + "\r" +
              (link_to_modal 'Edit Classes',
               course_edit_membership_path(registration.course, registration.member)
              ) + "\r" +
              (link_to "Remove", course_registration_path(registration),
                :method => 'delete',
                data: { confirm: 'Are you sure?' })
            end
          end
        end %>
      </div>
      <div class='course-attendance-history content <%= @tab == 'attendance' ? 'active': '' %>' id='course-attendance-history'>
        <%= render partial: 'courses/show/course_attendances', locals: { course: @course } %>
      </div>
      <div class='course-classes-table content <%= @tab.nil? || @tab == 'schedule' ? 'active' : '' %>'
        id='course-classes-table'>
        <%= render partial: 'courses/show/course_classes', locals: { course_classes_grid: @course_classes_grid, course: @course } %>
      </div>
    </div>
  </div>
</div>

app/views/courses/today.html.erb
<div class="row">
  <div class="small-8 large-centered columns">
    <h1 style='text-align: center'>Today's Classes:</h1>
  </div>
</div>
<div class="row">
  <div class="small-10 large-centered columns" id="courses-table">
    <%= render partial: "courses/today/today_classes",
      locals: { classes_grid: @classes_grid } %>
  </div>
</div>

app/views/courses/update.js.erb
<% if @course.errors.empty? %>
  $.modal.close();
  $("#courses-table").html('<%= escape_javascript(render(partial: "courses", locals: {courses_grid: @courses_grid })) %>')
  $('#flash').html("<%= escape_javascript raw(flash_display) %>");
  $('#flash').show();
<% else %>
  $("#edit").html('<%= escape_javascript(render(partial: "form", locals: { course: @course })) %>');
<% end %>