config/routes.rb
Members::Application.routes.draw do
  root 'check_in#checkin_page'

  get 'checkin', to: 'check_in#checkin_page'
  get 'checkin/histories', to: 'check_in#histories'
  post 'checkin', to: 'check_in#checkin'

  resources 'checkin', controller: "check_in", only: [:edit, :destroy, :update], as: "check_in"

  resources 'members', only: [:index, :show, :update, :create, :new, :destroy] do
    get 'edit', to: 'members#edit'
    get 'destroy_confirm'

    resources 'membership_registrations', only: [:create, :edit, :update, :new]

    delete 'avatar', to: 'avatar#destroy', as: :destroy_avatar
  end

  resources 'activities', only: [:index, :show, :update, :create, :new] do
    get 'edit', to: 'activites#edit'
  end

  resources 'sessions', only: [:create, :destroy, :new]
  get 'sessions/signout', to: 'sessions#destroy'

  resources 'course_instructors', only: [:index, :show, :update, :create, :new, :edit] do
  end

  get 'courses/calendar', to: 'courses#calendar'
  get 'courses/today', to: 'courses#today'
  get 'courses/:course_id/duplicate', to: 'courses#duplicate', as: :course_duplicate

  resources 'courses' do
    resources 'course_attendances', only: [:edit, :show, :update, :destroy]

    get 'member/:id/course_class/edit', to: 'course_class_memberships#edit', as: :edit_membership
    post 'member/:id/course_class', to: 'course_class_memberships#update', as: :update_membership

    resources 'course_classes', only: [:edit, :update, :destroy, :show, :new, :create]

    post 'update_attendance'
    post 'regenerate_classes'
  end

  get 'email_list_generator', :controller => :utils, :action => :email_list_generator

  resources 'course_registrations' do
    collection do
      get 'new_registration'
      post 'create_registration'
    end
  end

  resources 'books' do
    collection do
      get 'new_registration'
      post 'create_registration'
    end
    member do
      get 'mark_as_returned'
    end
  end

  resources 'book_rentals', :only => [:edit, :update, :create, :new] do
    collection do
      get 'return_a_book'
      post 'return_a_book', :to => 'book_rentals#do_return'
    end
  end
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_paper_trail
  has_many :check_ins, inverse_of: :activity
  before_validation :sanitize_name
  validates :name, presence: true, uniqueness: true
  belongs_to :location, inverse_of: :activities
  validates :location, presence: true

  scope :at_location, ->(location) { location.present? ? includes(:location).where(locations: {name: location}) : all }

  def sanitize_name
    self.name.capitalize!
  end

  def self.to_xls
    date = DateTime.now
    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet name: 'Activities'

    sheet1.row(0).replace(['Name'])
    index = 1
    Activity.all.each do |c|
      sheet1.row(index).replace([c.name])
      index += 1
    end

    return "activities_#{date.strftime('%Y%m%d')}.xls", book
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < AuthenticatedController
  before_action :set_activity, only: [:update, :show, :edit]

  def index
    @activities_grid = initialize_grid(Activity.at_location(@location), include: [:location])
    respond_to do |format|
      format.html {}
      format.xls {
        spreadsheet = StringIO.new
        name, book = Activity.to_xls
        book.write spreadsheet
        send_data spreadsheet.string, :filename => name, :type =>  "application/vnd.ms-excel"
      }
    end
  end

  def edit
    respond_to do | format |
      format.html {}
    end
  end

  def show
    respond_to do | format |
      format.html {}
    end
  end

  def update
    [:name].each do | f |
      @activity[f] = activity_params[f] if activity_params[f]
    end
    @activity.save
    flash[:notice] = "#{@activity.name} updated successfully" if @activity.errors.nil? || @activity.errors.empty?
    respond_to do | format |
      format.js {}
    end
    @activities = Activity.all
    @activities_grid = initialize_grid(Activity)
  end

  def create
    @activity = Activity.new(new_activity_params)
    @activity.save
    flash[:notice] = "#{@activity.name} created successfully" if @activity.errors.nil? || @activity.errors.empty?
    @activities_grid = initialize_grid(Activity)
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:name, :location_id)
  end

  def new_activity_params
    params.require(:activity).permit(:name, :location_id)
  end
end

app/views/activities/_activities.html.erb
<%= grid(@activities_grid, html: { style: 'width: 100%' }) do |g|
  g.column name: 'Name', attribute: 'name' do |activity|
    activity.name
  end

  g.column name: 'Location', model: 'Location', attribute: 'name' do |activity|
    activity.location.display_name
  end

  g.column do |activity|
    (link_to_modal 'Edit', activity)
  end
end
%>

app/views/activities/_form.html.erb
<% activity = Activity.new unless activity %>
<%= form_for(activity, remote: true) do |f| %>
  <%= f.text_field :name %>
  <%= f.label 'Location' %>
  <%= f.collection_select :location_id, Location.order(:name), :id, :display_name, prompt: 'Select Location' %>
  <%= f.submit %>
<% end %>

app/views/activities/create.js.erb
<% if @activity.errors.nil? || @activity.errors.empty? %>
  $.modal.close();
  $("#activities-table").html('<%= escape_javascript(render(partial: "activities", locals: { activities: @activities } )) %>')
  $('#flash').html("<%= escape_javascript raw(flash_display) %>");
  $('#flash').show();
<% else %>
  $(".activity_form").html('<%= escape_javascript(render(partial: "form", locals: { activity: @activity })) %>');
<% end %>

app/views/activities/edit.html.erb
<div class="activity_form" id="form_<%= dom_id(@activity) %>">
  <%= render partial: "form", locals: { activity: @activity } %>
</div>

app/views/activities/index.html.erb
<div class="row">
  <div class="small-8 large-centered columns">
    <h1 style='text-align: center'>All Activites:</h1>
  </div>
</div>
<div class="row">
  <div class="small-10 large-centered columns" style="padding-bottom: 10px">
    <%= link_to_modal "New", new_activity_path, class: 'button small' %>
    <%= link_to("Export", activities_path(format: :xls), class: 'button small') %>
  </div>
</div>
<div class="row">
  <div class="small-10 large-centered columns" id="activities-table">
    <%= render partial: "activities", locals: { activities: @activities } %>
  </div>
</div>

app/views/activities/new.html.erb
<div class="activity_form" id="form_new">
  <%= render partial: "form" %>
</div

app/views/activities/show.html.erb
<div class="activity_form" id="form_<%= dom_id(@activity) %>">
  <%= render partial: "form", locals: { activity: @activity } %>
</div

app/views/activities/update.js.erb
<% if @activity.errors.nil? || @activity.errors.empty? %>
  $.modal.close();
  $("#activities-table").html('<%= escape_javascript(render(partial: "activities", locals: { activities: @activities } )) %>')
<% else %>
  $(".activity_form").html('<%= escape_javascript(render(partial: "form", locals: { activity: @activity })) %>');
<% end %>